spring:
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true
    open-in-view: false

  datasource:
    url: jdbc:mysql://localhost:3306/ems?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver